-- Synthetic MVP decision cycle. Run once.
-- The execution event is simulated; no Cloud Batch job has been submitted yet.

INSERT INTO `greencompute_events.workload_run_events` VALUES (
  'event-workload-requested-001',
  'org-retail-demo',
  'wr-nightly-sales-001',
  'wdv-nightly-sales-v1',
  'pv-india-high-reliability-v1',
  'demo-idempotency-001',
  'corr-nightly-sales-001',
  'WORKLOAD_RUN_REQUESTED',
  'REQUESTED',
  CURRENT_TIMESTAMP(),
  'Asia/Kolkata',
  CURRENT_TIMESTAMP(),
  TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR),
  'USER',
  'demo-admin',
  JSON '{"data_asset_version_id":"dav-sales-india-v1"}',
  1,
  CURRENT_TIMESTAMP()
);

INSERT INTO `greencompute_events.optimization_runs` VALUES (
  'opt-nightly-sales-001',
  'org-retail-demo',
  'wr-nightly-sales-001',
  'wdv-nightly-sales-v1',
  'pv-india-high-reliability-v1',
  'corr-nightly-sales-001',
  'optimizer-mvp-v1',
  'COMPLETED',
  JSON '{"priority_order":["hard_constraints","reliability","cost","carbon"]}',
  [
    'price-mumbai-standard-v1',
    'price-mumbai-spot-v1',
    'price-delhi-standard-v1',
    'carbon-mumbai-v1',
    'carbon-delhi-v1'
  ],
  CURRENT_TIMESTAMP(),
  CURRENT_TIMESTAMP(),
  JSON '{"metric_source":"MVP_SYNTHETIC","all_metrics_synthetic":true}',
  1,
  CURRENT_TIMESTAMP()
);

INSERT INTO `greencompute_events.candidate_evaluations` VALUES
  (
    'candidate-mumbai-spot-001',
    'opt-nightly-sales-001',
    'org-retail-demo',
    'wr-nightly-sales-001',
    'asia-south1',
    CURRENT_TIMESTAMP(),
    TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 3 HOUR),
    'n2-standard-8',
    'SPOT',
    0.48,
    0.00,
    'USD',
    60,
    NULL,
    0.85,
    0.75,
    32400,
    FALSE,
    ['RELIABILITY_BELOW_POLICY_THRESHOLD'],
    NULL,
    NULL,
    JSON '{"source":"MVP_SYNTHETIC"}',
    CURRENT_TIMESTAMP(),
    1,
    CURRENT_TIMESTAMP()
  ),
  (
    'candidate-mumbai-standard-001',
    'opt-nightly-sales-001',
    'org-retail-demo',
    'wr-nightly-sales-001',
    'asia-south1',
    CURRENT_TIMESTAMP(),
    TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 3 HOUR),
    'n2-standard-8',
    'STANDARD',
    1.20,
    0.00,
    'USD',
    60,
    NULL,
    0.99,
    0.95,
    32400,
    TRUE,
    [],
    2,
    2,
    JSON '{"source":"MVP_SYNTHETIC"}',
    CURRENT_TIMESTAMP(),
    1,
    CURRENT_TIMESTAMP()
  ),
  (
    'candidate-delhi-standard-001',
    'opt-nightly-sales-001',
    'org-retail-demo',
    'wr-nightly-sales-001',
    'asia-south2',
    CURRENT_TIMESTAMP(),
    TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 3 HOUR),
    'n2-standard-8',
    'STANDARD',
    1.08,
    0.02,
    'USD',
    45,
    NULL,
    0.99,
    0.98,
    32400,
    TRUE,
    [],
    1,
    1,
    JSON '{"source":"MVP_SYNTHETIC"}',
    CURRENT_TIMESTAMP(),
    1,
    CURRENT_TIMESTAMP()
  );

INSERT INTO `greencompute_events.policy_evaluations` VALUES
  (
    'policy-eval-mumbai-spot-001',
    'candidate-mumbai-spot-001',
    'opt-nightly-sales-001',
    'pv-india-high-reliability-v1',
    'org-retail-demo',
    'MINIMUM_RELIABILITY',
    'RELIABILITY',
    FALSE,
    JSON '0.90',
    JSON '0.85',
    'Spot reliability is below the policy minimum.',
    CURRENT_TIMESTAMP(),
    1,
    CURRENT_TIMESTAMP()
  ),
  (
    'policy-eval-mumbai-standard-001',
    'candidate-mumbai-standard-001',
    'opt-nightly-sales-001',
    'pv-india-high-reliability-v1',
    'org-retail-demo',
    'MINIMUM_RELIABILITY',
    'RELIABILITY',
    TRUE,
    JSON '0.90',
    JSON '0.99',
    'Standard capacity meets the policy minimum.',
    CURRENT_TIMESTAMP(),
    1,
    CURRENT_TIMESTAMP()
  ),
  (
    'policy-eval-delhi-standard-001',
    'candidate-delhi-standard-001',
    'opt-nightly-sales-001',
    'pv-india-high-reliability-v1',
    'org-retail-demo',
    'MINIMUM_RELIABILITY',
    'RELIABILITY',
    TRUE,
    JSON '0.90',
    JSON '0.99',
    'Standard capacity meets the policy minimum.',
    CURRENT_TIMESTAMP(),
    1,
    CURRENT_TIMESTAMP()
  );

INSERT INTO `greencompute_events.optimization_decisions` VALUES (
  'decision-nightly-sales-001',
  'opt-nightly-sales-001',
  'candidate-delhi-standard-001',
  'org-retail-demo',
  'wr-nightly-sales-001',
  'SELECTED',
  TRUE,
  1,
  'Selected because it meets all hard constraints and reliability requirements, with lower estimated cost and carbon score than the valid Mumbai Standard alternative.',
  JSON '{"metric_source":"MVP_SYNTHETIC","spot_candidate_rejected_for_reliability":true}',
  'candidate-mumbai-standard-001',
  1.10,
  'USD',
  45,
  0.99,
  32400,
  CURRENT_TIMESTAMP(),
  1,
  CURRENT_TIMESTAMP()
);

INSERT INTO `greencompute_events.execution_events` VALUES (
  'event-execution-simulated-001',
  'org-retail-demo',
  'wr-nightly-sales-001',
  'decision-nightly-sales-001',
  'attempt-nightly-sales-001',
  'GCP',
  'SIMULATED-BATCH-JOB-001',
  1,
  'SIMULATED_EXECUTION_COMPLETED',
  'SUCCEEDED',
  CURRENT_TIMESTAMP(),
  'asia-south2',
  10560,
  1.10,
  'USD',
  FALSE,
  NULL,
  NULL,
  JSON '{"is_simulated":true,"note":"Replace with Google Cloud Batch event after integration."}',
  'corr-nightly-sales-001',
  1,
  CURRENT_TIMESTAMP()
);

INSERT INTO `greencompute_audit.audit_events` VALUES (
  'audit-decision-created-001',
  'org-retail-demo',
  'SYSTEM',
  'greencompute-optimizer',
  'OPTIMIZATION_DECISION_CREATED',
  'SUCCESS',
  'OPTIMIZATION_DECISION',
  'decision-nightly-sales-001',
  'corr-nightly-sales-001',
  'demo-idempotency-001',
  CURRENT_TIMESTAMP(),
  NULL,
  JSON '{"environment":"MVP"}',
  JSON '{"is_synthetic":true}',
  1,
  CURRENT_TIMESTAMP()
);
